today-i-feel/config/routes.rb
Rails.application.routes.draw do

devise_for :users
resources :emotions, only: [:index, :show]
resources :quotes, only: [:new, :create, :destroy]
resources :images, only: [:new, :create, :destroy]
resources :videos, only: [:new, :create, :destroy]

root 'emotions#index'

end

today-i-feel/app/models/emotion.rb
class Emotion < ActiveRecord::Base
  has_many :quotes
  has_many :videos
  has_many :images
  validates :name, uniqueness: true
end

today-i-feel/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :emotion
  belongs_to :user
end

today-i-feel/app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :emotion
  belongs_to :user
end

today-i-feel/app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  has_many :videos
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

today-i-feel/app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :emotion
  belongs_to :user
end

today-i-feel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

today-i-feel/app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
# before_action :authenticate_user!
# THE SYNTAX ABOVE BLOCKS ACCESS TO ALL THESE FEATURES AND REDIRECTS
# TO THE SIGN UP PAGE IF THE SITE VISITOR IS NOT LOGGED IN

# before_action :authenticate_user!, :except => [:show, :index]
# QUICK AND CHEAP WAY TO SPECIFY WHICH TO NOT DO

  def index
    @emotions = Emotion.all
    @emotions = @emotions.sample(@emotions.length) #randomize opening presentaiton
  end


  def show
    @emotion = Emotion.find(params[:id])
    # USER 1 is the Admin ID.
    if user_signed_in?
      ## QUOTES
      @quotes = Quote.where(user_id: 1, emotion: @emotion)
      @user_content = Quote.where(user: current_user, emotion: @emotion)
      @quotes = @quotes.concat(@user_content) if !@user_content.empty?
      @quotes = @quotes.sample(4) #randomize quotes with max 4

      ## VIDEOS
      @videos = Video.where(user_id: 1, emotion: @emotion)
      @user_content = Video.where(user: current_user, emotion: @emotion)
      @videos = @videos.concat(@user_content) if !@user_content.empty?
      @videos = @videos.sample(3) #randomize videos with max 3
      
      ## IMAGES
      @images = Image.where(user_id: 1, emotion: @emotion)
      @user_content = Image.where(user: current_user, emotion: @emotion)
      @images = @images.concat(@user_content) if !@user_content.empty?
      @images = @images.sample(2) #randomize videos with max 2
    


    else
      ## QUOTES
      @quotes = Quote.where(user_id: 1, emotion: @emotion)
      @quotes = @quotes.sample(4) #randomize quotes with max 4

      ## VIDEOS
      @videos = Video.where(user_id: 1, emotion: @emotion)
      @videos = @videos.sample(4) #randomize videos with max 3
      
      ## IMAGES
      @images = Image.where(user_id: 1, emotion: @emotion)
      @images = @images.sample(2) #randomize videos with max 2
    end  
  end

end

today-i-feel/app/controllers/images_controller.rb
class ImagesController < ApplicationController
# before_action :authenticate_user!
  def new
    @image = Image.new
  end  

  def create
    image = params[:image]
    emotion = Emotion.find_by(name: params[:emotion])
    # Fix url to be in embedded format from share format:

    url = image[:url]

    final_hash = { name: image[:name], url: url, emotion: emotion, user: current_user }
    @image = Image.create(final_hash)
    if @image.valid?
      redirect_to root_path
    else
      "ahhhhh!"
    end
  end

  def destroy
    @image = Image.find(params[:id])
    emotion = @image.emotion
    @image.destroy if @image.user = current_user
    redirect_to emotion_path(emotion)
  end

end

today-i-feel/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
# before_action :authenticate_user!
def new
  @quotes = Quote.new
end  

def create
  quote = params[:quote]
  emotion = Emotion.find_by(name: params[:emotion])
  final_hash = { emotion: emotion, user: current_user }

  @quote = Quote.new(quotes_params)
  @quote.update(final_hash)

  if @quote.valid?
    @quote.save
    redirect_to root_path
  else
    "ahhhhh!"
  end
end

def destroy
  @quote = Quote.find(params[:id])
  emotion = @quote.emotion
  @quote.destroy if @quote.user = current_user
  redirect_to emotion_path(emotion)
end


private
  def quotes_params
    params.require(:quote).permit(:body, :author)
  end

end

today-i-feel/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
  end

end

today-i-feel/app/controllers/videos_controller.rb
class VideosController < ApplicationController
# before_action :authenticate_user!
  def new
    @video = Video.new
  end  

  def create
    video = params[:video]
    emotion = Emotion.find_by(name: params[:emotion])
    # Fix url to be in embedded format from share format:

    starting_url = video[:embedded_url]
    leading_nonsense = "https://youtu.be".length
    total_length = starting_url.length
    stripped_url = starting_url[leading_nonsense..total_length]
    url = "https://www.youtube.com/embed" + stripped_url

    final_hash = { name: video[:name], embedded_url: url, emotion: emotion, user: current_user }
    @video = Video.create(final_hash)
    if @video.valid?
      redirect_to root_path
    else
      "ahhhhh!"
    end
  end

  def destroy
    @video = Video.find(params[:id])
    emotion = @video.emotion
    @video.destroy if @video.user = current_user
    redirect_to emotion_path(emotion)
  end

end

today-i-feel/app/helpers/application_helper.rb
module ApplicationHelper
end

today-i-feel/app/views/User/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

today-i-feel/app/views/emotions/index.html.erb
<h1 class="question hidden">How Do You Feel Today?</h1>

<% @emotions.each do |emotion| %>
  <div class="emotional-state circle" id='<%= emotion.name.downcase %>'>
    <h2 class="emotional-text hidden" id='<%= emotion.name.downcase %>-text'><%= link_to "#{emotion.name}", emotion_path(emotion), class: "emotional-text hidden" %></h2>
  </div>
<%end%>

today-i-feel/app/views/emotions/show.html.erb
<div class="show-emotion-page hidden">
  <h1 class="emotion-header"> <%=@emotion.name %> </h1>

  <section class="quote-display">
    <% @quotes.each do |quote| %>
      <p class="quote-body"> <%= quote.body %> </p>
      <p class="quote-author"><%= link_to "#{quote.author}", Wikipedia.find(quote.author).fullurl %></p>
      <% if quote.user == current_user %>
        <p class="link hidden"><%= link_to "Get rid of it", quote_path(quote), method: :delete %></p>
      <% end %>

    <% end %>
  </section>

  <section class="video">
    <% @videos.each do |video| %>
      <iframe class="individual-video" width="250" height="215" src="<%=video.embedded_url%>" frameborder="0" allowfullscreen></iframe>
        <% if video.user == current_user %>
          <p class="link hidden"><%= link_to "Get rid of it", video_path(video), method: :delete %></p>
        <% end %>
      <% end %>
  </section>

  <section class="images">
    <% @images.each do |image| %>
      <%= image_tag(image.url, size: "400x250", alt: "Pretty Picture", class: "individual-image") %>
        <% if image.user == current_user %>
          <p class="link hidden"><%= link_to "Get rid of it", image_path(image), method: :delete %></p>
        <% end %>
    <% end %>    
  </section>
</div>

today-i-feel/app/views/images/new.html.erb
<h1>Add a new image</h1>

<%= form_for :image, url: images_path, method: :post do |f| %>
  <p class="form-tags">Name: </p><%= f.text_field :name %><br />
  <p class="form-tags url">Url: </p><%= f.text_field :url, :required => true %><br />
  <p class="form-tags">Emotion: </p><%= select_tag(:emotion, options_for_select([['Happy'], ['Sad'], ['Numb'], ['Angry'], ['Lost']])) %><br /><br />
  <%= f.submit %>
<% end %>

today-i-feel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodayIFeel</title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Poppins:400,700' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav-bar">
    <p class="link"><%= link_to "Home", root_path %></p>
  <% if !user_signed_in? %>
    <div class="sessions-options">
      <p class="link"><%= link_to "Sign Up is super optional     |", new_user_registration_path %></p>
      <p class="link"><%= link_to "Sign In", new_user_session_path %></p>
    </div>
  <% end  %>
  <% if user_signed_in? %>
  <div class="creation-options">
      <p class="link"><%= link_to "Add Quote", new_quote_path %></p>
      <p class="link"><%= link_to "Add Video", new_video_path %></p>
      <p class="link"><%= link_to "Add Image", new_image_path %></p>
    </div>
  <% end  %>
  <% if user_signed_in? %>
  <div class="sessions-options">
      <p class="link"><%= link_to "I'm Done", destroy_user_session_path, method: :delete %></p>
    </div>
  <% end  %>
  </div>
<%= yield %>

</body>
</html>

today-i-feel/app/views/quotes/new.html.erb
<h1>Add a new quote</h1>

<%= form_for :quote, url: quotes_path, method: :post do |f| %>
  <p class="form-tags"> Body: </p> <%= f.text_area :body, cols: "30", rows: "5", :required => true %><br />
  <p class="form-tags"> Author: </p> <%= f.text_field :author, :required => true %><br />
  <p class="form-tags"> Emotion: </p> <%= select_tag(:emotion, options_for_select([['Happy'], ['Sad'], ['Numb'], ['Angry'], ['Lost']])) %><br /><br />
  <%= f.submit %>
<% end %>

today-i-feel/app/views/videos/new.html.erb
<h1>Add a new video</h1>

<%= form_for :video, url: videos_path, method: :post do |f| %>
  <p class="form-tags">Name: </p> <%= f.text_field :name %><br />
  <p class="form-tags url">Url: </p><%= f.text_field :embedded_url, :required => true %><br />
  <p class="form-tags">Emotion: </p><%= select_tag(:emotion, options_for_select([['Happy'], ['Sad'], ['Numb'], ['Angry'], ['Lost']])) %><br /><br />
  <%= f.submit %>
<% end %>